### ISSUE TITLE
Server config location issue

### ISSUE THREAD

**Issue by thomas2108** [d3vilh/openvpn-ui#47]
On most default installation the server.conf location is /etc/openvpn. The openvpn-ui code requires hardwired a <serverdir>/config/server.conf directory in controllers/ovconfig.go. 
This should be parametrized so default installation will become supported.
The location of the client.conf might also be a parameter.

**Comment by d3vilh** [comment]
Hi @thomas2108  it is known issue.
It is preconfigured this way historically, due to I used subdir `config` for server and client config files separation.
I planned to change it eventually in the ver 1.0 to announce *important configuration change* between the major versions, as it will demand to adjust server side configuration for all the config trees with `config` subdirectories.

I'll think on it, maybe will add some automation in backend to move all the files smoothly, or just announce it, so humans will aware of the changes.

**Comment by d3vilh** [comment]
So, Mr. @thomas2108 it seems I forced to change this default configuration, as there is demand from other users as well :D
I'll try to do it and rebuild all the containers accordingly.
Cheers.
