### ISSUE TITLE
Standalone Install Username/Password

### ISSUE THREAD

**Issue by Alex-Giaquinto** [d3vilh/openvpn-ui#52]
I just tried doing the standalone install a few times and every time after following the instructions I cannot login. I use the export commands for both username and password but cannot get in.

**Comment by d3vilh** [comment]
Hi @Alex-Giaquinto,
Thanks for the reporting.
Vars export should be done before the first start of the container (otherwise it will not create user correctly).

For you solution will be following:
Stop application. Drop database file:
```bash
kalimera@kaliserver:~/openvpn-server/db $ rm data.db
rm: remove write-protected regular file 'data.db'? yes
```
this will clear all UI users configuration. 

Then run export again:
```bash
export OPENVPN_ADMIN_USERNAME=admin
export OPENVPN_ADMIN_PASSWORD=MyPassword

```
Double check that environment is updated properly
```bash
echo $OPENVPN_ADMIN_USERNAME
echo $OPENVPN_ADMIN_PASSWORD

The output will be:
admin
MyPassword
```

Then start application again. It will create all the users and hash your password into DB. 
For security reasons **you have to unset** these vars after success login, so it will be removed from the local server environment:

```bash
unset OPENVPN_ADMIN_USERNAME
unset OPENVPN_ADMIN_PASSWORD
```
This username and password export needs to be done only once, on the first application run, when application creates DB and users for access.

**Comment by Alex-Giaquinto** [comment]
Hey! @d3vilh sorry for the late reply. Thanks for the detailed response! So I did all of this and I am still unable to get in. Anything I can show you that might help?

**Comment by d3vilh** [comment]
> Anything I can show you that might help?

Hi @Alex-Giaquinto, sorry for the late reply! My main job has been super demanding lately 🙃

Yes, if you could share your session log, like commands you execute one by one with output it would be very nice (hide passwords) and running application log.
This would help with debugging.

I also did short update for [Standalone installation procedure](https://github.com/d3vilh/openvpn-ui?tab=readme-ov-file#standalone-installation-without-docker-and-docker-compose).

**Comment by d3vilh** [comment]
Pin this one and closing.
